using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace SurfaceSystem
{
    /// <summary>
    /// Implements the "Compile" step of a <see cref="SurfaceData"/>: makes sure every group has a unique,
    /// stable id, then regenerates <c>SurfaceGroups.cs</c> - only if its content actually changed, so compiling
    /// without renaming anything never triggers a script reload.
    /// </summary>
    internal static class SurfaceCompiler
    {
        private const string GeneratedFolder = "Assets/Scripts/SurfaceEngine/Runtime/Generated/";

        public static void Compile(SurfaceData data)
        {
            Undo.RecordObject(data, "Compile Surface Data");
            if (data.EnsureUniqueIds())
            {
                EditorUtility.SetDirty(data);
            }

            var members = new List<KeyValuePair<string, int>>();
            var names = new HashSet<string>(StringComparer.Ordinal);

            foreach (var group in data.Groups)
            {
                if (group == null)
                {
                    continue;
                }

                var name = ToIdentifier(group.Header);
                if (name == null || name == nameof(SurfaceGroups.None) || !names.Add(name))
                {
                    Debug.LogError($"[SurfaceData] The surface '{group.Header}' has an empty, reserved ('None') or repeated name. " +
                                    "Every surface needs a unique name - it becomes its SurfaceGroups member. Compile aborted.", data);
                    return;
                }

                members.Add(new KeyValuePair<string, int>(name, group.Id));
            }

            if (members.Count == 0)
            {
                Debug.LogError("[SurfaceData] There is no surface group. Add one first. Compile aborted.", data);
                return;
            }

            AssetDatabase.SaveAssets();

            var changed = WriteEnum(members, out var path);
            if (changed)
            {
                AssetDatabase.ImportAsset(path);
            }

            Debug.Log($"[SurfaceData] Compile finished: {members.Count} surface(s)." + (changed ? " Scripts are recompiling." : string.Empty));
        }

        /// <summary>Writes <c>SurfaceGroups.cs</c>; returns false (and writes nothing) if it already has this content.</summary>
        private static bool WriteEnum(List<KeyValuePair<string, int>> members, out string assetPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by SurfaceData > Compile. Do not edit by hand - it is overwritten every time a");
            sb.AppendLine("// SurfaceData asset is compiled. Every value is the group's stable id, so reordering or removing");
            sb.AppendLine("// groups never shifts the value of a SurfaceGroups already saved in a scene or prefab.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace SurfaceSystem");
            sb.AppendLine("{");
            sb.AppendLine("    public enum SurfaceGroups");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");
            foreach (var member in members)
            {
                sb.AppendLine($"        {member.Key} = {member.Value},");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            assetPath = FindGeneratedPath();
            var fullPath = Path.Combine(Directory.GetParent(Application.dataPath)!.FullName,
                assetPath.Replace('/', Path.DirectorySeparatorChar));

            var source = sb.ToString();
            if (File.Exists(fullPath) && NormalizeNewlines(File.ReadAllText(fullPath)) == NormalizeNewlines(source))
            {
                return false;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            File.WriteAllText(fullPath, source);
            return true;
        }

        // Follows the file if the SurfaceSystem folder was moved; falls back to the default location.
        private static string FindGeneratedPath()
        {
            foreach (var guid in AssetDatabase.FindAssets("SurfaceGroups t:MonoScript"))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.EndsWith("/Generated/SurfaceGroups.cs", StringComparison.Ordinal))
                {
                    return path;
                }
            }

            return GeneratedFolder + "SurfaceGroups.cs";
        }

        private static string NormalizeNewlines(string text) => text.Replace("\r\n", "\n");

        // "Deep Snow" -> "DeepSnow", "ak-47" -> "Ak47", "9mm Ammo" -> "_9mmAmmo".
        private static string ToIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
            {
                return null;
            }

            var sb = new StringBuilder();
            var capitalizeNext = true;
            foreach (var c in raw.Trim())
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                    capitalizeNext = false;
                }
                else
                {
                    capitalizeNext = true;
                }
            }

            if (sb.Length == 0)
            {
                return null;
            }

            if (char.IsDigit(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }
    }
}
